version: '2'

services: 
  web:
    image: php54-apache
    ports:
      - "80:80"
    depends_on:
      - mysql
    links: 
      - mysql
    volumes:
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
      
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pimcore2
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
    volumes: 
      - ./.db-data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "88:80"
